export const ORDER_PURCHASE_INIT = "ORDER_PURCHASE_INIT";
export const ORDER_PURCHASE_START = "ORDER_PURCHASE_START";
export const ORDER_PURCHASE_SUCCESS = "ORDER_PURCHASE_SUCCESS";
export const ORDER_PURCHASE_FAIL = "ORDER_PURCHASE_FAIL";
export const ORDER_FETCH_START = "ORDER_FETCH_START";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAIL = "ORDER_FETCH_FAIL";
